"""Feature catalog: 129 declared features (implemented + declared-not-implemented).

Each entry maps to the master-prompt section 31. Implemented modules are real
classes in this package; the rest are declared here with ``not_implemented=True``
so they appear in the panel and are gated by the plugin system.
"""

from __future__ import annotations

CATALOG: list[dict] = [
    # ---- message ----
    {"key": "regex_reply", "name": "پاسخ با الگو", "category": "message", "description": "پاسخ بر اساس الگوی Regex"},
    {"key": "auto_delete", "name": "حذف خودکار", "category": "message", "description": "حذف خودکار پیام‌ها پس از مدت مشخص"},
    {"key": "auto_edit", "name": "ویرایش خودکار", "category": "message", "description": "ویرایش خودکار پیام‌ها"},
    {"key": "message_filter", "name": "فیلتر پیام", "category": "message", "description": "فیلتر پیام‌های ورودی"},
    {"key": "word_filter", "name": "فیلتر کلمه", "category": "message", "description": "فیلتر کلمات نامناسب"},
    {"key": "link_filter", "name": "فیلتر لینک", "category": "message", "description": "فیلتر لینک‌ها"},
    {"key": "media_filter", "name": "فیلتر رسانه", "category": "message", "description": "فیلتر فایل‌های رسانه‌ای"},
    {"key": "message_logger", "name": "ثبت پیام", "category": "message", "description": "ثبت پیام‌ها در گزارش"},
    {"key": "message_search", "name": "جستجوی پیام", "category": "message", "description": "جستجوی پیام در چت‌ها"},
    {"key": "message_stats", "name": "آمار پیام", "category": "message", "description": "آمار پیام‌ها"},
    {"key": "auto_read", "name": "خواندن خودکار", "category": "message", "description": "خواندن خودکار پیام‌ها"},
    {"key": "auto_typing", "name": "تایپ خودکار", "category": "message", "description": "نمایش وضعیت تایپ خودکار"},
    {"key": "scheduled_messages", "name": "پیام زمان‌بندی", "category": "message", "description": "ارسال پیام زمان‌بندی‌شده"},
    # ---- groups ----
    {"key": "goodbye", "name": "خداحافظی", "category": "groups", "description": "پیام خداحافظی هنگام خروج عضو"},
    {"key": "anti_spam", "name": "ضد اسپم", "category": "groups", "description": "تشخیص و حذف اسپم"},
    {"key": "anti_flood", "name": "ضد سیل", "category": "groups", "description": "جلوگیری از ارسال سیل‌وار"},
    {"key": "anti_fake", "name": "ضد اکانت فیک", "category": "groups", "description": "تشخیص اکانت‌های جعلی"},
    {"key": "warn", "name": "اخطار", "category": "groups", "description": "سیستم اخطار کاربران"},
    {"key": "mute", "name": "سکوت", "category": "groups", "description": "ساکت کردن کاربر"},
    {"key": "unmute", "name": "لغو سکوت", "category": "groups", "description": "رفع سکوت کاربر"},
    {"key": "ban", "name": "بن", "category": "groups", "description": "بن کردن کاربر"},
    {"key": "unban", "name": "آنبن", "category": "groups", "description": "رفع بن کاربر"},
    {"key": "kick", "name": "اخراج", "category": "groups", "description": "اخراج کاربر از گروه"},
    {"key": "admin_manager", "name": "مدیریت ادمین", "category": "groups", "description": "مدیریت ادمین‌های گروه"},
    {"key": "purge", "name": "پاکسازی", "category": "groups", "description": "حذف دسته‌جمعی پیام‌ها"},
    {"key": "group_stats", "name": "آمار گروه", "category": "groups", "description": "آمار اعضا و فعالیت گروه"},
    # ---- channels ----
    {"key": "scheduled_posts", "name": "پست زمان‌بندی", "category": "channels", "description": "زمان‌بندی پست کانال"},
    {"key": "auto_forward", "name": "فوروارد خودکار", "category": "channels", "description": "فوروارد خودکار پیام به کانال"},
    {"key": "post_templates", "name": "قالب پست", "category": "channels", "description": "قالب‌های آماده پست"},
    {"key": "channel_auto_delete", "name": "حذف خودکار کانال", "category": "channels", "description": "حذف خودکار پست‌ها"},
    {"key": "post_stats", "name": "آمار پست", "category": "channels", "description": "آمار بازدید پست‌ها"},
    {"key": "media_publishing", "name": "انتشار رسانه", "category": "channels", "description": "انتشار خودکار رسانه"},
    {"key": "caption_manager", "name": "مدیریت کپشن", "category": "channels", "description": "مدیریت کپشن پست‌ها"},
    {"key": "hashtag_manager", "name": "مدیریت هشتگ", "category": "channels", "description": "مدیریت هشتگ‌ها"},
    {"key": "channel_monitor", "name": "مانیتور کانال", "category": "channels", "description": "پایش کانال‌ها"},
    {"key": "cross_posting", "name": "پست‌گذاری متقاطع", "category": "channels", "description": "انتشار هم‌زمان در چند کانال"},
    # ---- automation ----
    {"key": "trigger_engine", "name": "موتور تریگر", "category": "automation", "description": "موتور تریگر رویدادها"},
    {"key": "rule_engine", "name": "موتور قانون", "category": "automation", "description": "موتور قوانین"},
    {"key": "event_action", "name": "رویداد و عمل", "category": "automation", "description": "نگاشت رویداد به عمل"},
    {"key": "scheduler_core", "name": "زمان‌بند", "category": "automation", "description": "زمان‌بندی وظایف"},
    {"key": "recurring_tasks", "name": "وظایف تکراری", "category": "automation", "description": "وظایف تکراری"},
    {"key": "conditions", "name": "شرط‌ها", "category": "automation", "description": "شرط‌های قانون"},
    {"key": "workflows", "name": "گردش‌کار", "category": "automation", "description": "گردش‌کارهای چندمرحله‌ای"},
    {"key": "forward_rules", "name": "قوانین فوروارد", "category": "automation", "description": "قوانین فوروارد خودکار"},
    {"key": "reply_rules", "name": "قوانین پاسخ", "category": "automation", "description": "قوانین پاسخ خودکار"},
    {"key": "user_rules", "name": "قوانین کاربر", "category": "automation", "description": "قوانین بر اساس کاربر"},
    {"key": "chat_rules", "name": "قوانین چت", "category": "automation", "description": "قوانین بر اساس چت"},
    {"key": "time_rules", "name": "قوانین زمان", "category": "automation", "description": "قوانین بر اساس زمان"},
    {"key": "regex_rules", "name": "قوانین Regex", "category": "automation", "description": "قوانین مبتنی بر الگو"},
    {"key": "webhook_trigger", "name": "تریگر وب‌هوک", "category": "automation", "description": "فعال‌سازی با وب‌هوک"},
    {"key": "api_trigger", "name": "تریگر API", "category": "automation", "description": "فعال‌سازی با API"},
    # ---- media ----
    {"key": "downloader", "name": "دانلودر", "category": "media", "description": "دانلود رسانه از پیام"},
    {"key": "uploader", "name": "آپلودر", "category": "media", "description": "آپلود فایل"},
    {"key": "rename", "name": "تغییر نام", "category": "media", "description": "تغییر نام فایل‌ها"},
    {"key": "image_tools", "name": "ابزار تصویر", "category": "media", "description": "ابزارهای پردازش تصویر"},
    {"key": "video_tools", "name": "ابزار ویدیو", "category": "media", "description": "ابزارهای پردازش ویدیو"},
    {"key": "audio_tools", "name": "ابزار صدا", "category": "media", "description": "ابزارهای پردازش صدا"},
    {"key": "voice_tools", "name": "ابزار ویس", "category": "media", "description": "ابزارهای پردازش ویس"},
    {"key": "file_info", "name": "اطلاعات فایل", "category": "media", "description": "نمایش اطلاعات فایل"},
    {"key": "thumbnail", "name": "تصویر بندانگشتی", "category": "media", "description": "ساخت تصویر بندانگشتی"},
    {"key": "converter", "name": "تبدیل‌گر", "category": "media", "description": "تبدیل فرمت رسانه"},
    # ---- search ----
    {"key": "user_info", "name": "اطلاعات کاربر", "category": "search", "description": "نمایش اطلاعات کاربر"},
    {"key": "chat_info", "name": "اطلاعات چت", "category": "search", "description": "نمایش اطلاعات چت"},
    {"key": "message_info", "name": "اطلاعات پیام", "category": "search", "description": "نمایش اطلاعات پیام"},
    {"key": "id_finder", "name": "یافتن ID", "category": "search", "description": "یافتن شناسه‌ها"},
    {"key": "message_search2", "name": "جستجوی پیام", "category": "search", "description": "جستجوی پیشرفته پیام"},
    {"key": "user_search", "name": "جستجوی کاربر", "category": "search", "description": "جستجوی کاربران"},
    {"key": "chat_search", "name": "جستجوی چت", "category": "search", "description": "جستجوی چت‌ها"},
    {"key": "history_search", "name": "جستجوی تاریخچه", "category": "search", "description": "جستجو در تاریخچه"},
    {"key": "link_extractor", "name": "استخراج لینک", "category": "search", "description": "استخراج لینک‌ها"},
    {"key": "statistics", "name": "آمار", "category": "search", "description": "آمار و گزارش‌ها"},
    # ---- plugins ----
    {"key": "plugin_manager", "name": "مدیر پلاگین", "category": "plugins", "description": "مدیریت پلاگین‌ها"},
    {"key": "plugin_toggle", "name": "فعال/غیرفعال پلاگین", "category": "plugins", "description": "فعال‌سازی پلاگین"},
    {"key": "plugin_config", "name": "پیکربندی پلاگین", "category": "plugins", "description": "تنظیمات پلاگین"},
    {"key": "plugin_reload", "name": "بارگذاری مجدد", "category": "plugins", "description": "بارگذاری مجدد پلاگین"},
    {"key": "plugin_deps", "name": "وابستگی‌ها", "category": "plugins", "description": "مدیریت وابستگی پلاگین"},
    {"key": "plugin_permissions", "name": "مجوزها", "category": "plugins", "description": "مجوزهای پلاگین"},
    {"key": "plugin_versioning", "name": "نسخه‌بندی", "category": "plugins", "description": "نسخه‌بندی پلاگین"},
    {"key": "plugin_logs", "name": "لاگ پلاگین", "category": "plugins", "description": "گزارش پلاگین‌ها"},
    {"key": "plugin_marketplace", "name": "بازارچه پلاگین", "category": "plugins", "description": "بازارچه پلاگین"},
    {"key": "custom_plugins", "name": "پلاگین سفارشی", "category": "plugins", "description": "پلاگین‌های سفارشی"},
    # ---- system ----
    {"key": "sys_start", "name": "شروع", "category": "system", "description": "شروع سلف"},
    {"key": "sys_stop", "name": "توقف", "category": "system", "description": "توقف سلف"},
    {"key": "sys_restart", "name": "ری‌استارت", "category": "system", "description": "ری‌استارت سلف"},
    {"key": "sys_health", "name": "سلامت", "category": "system", "description": "وضعیت سلامت سلف"},
    {"key": "config_reload", "name": "بارگذاری کانفیگ", "category": "system", "description": "بارگذاری مجدد تنظیمات"},
    {"key": "backup", "name": "پشتیبان‌گیری", "category": "system", "description": "پشتیبان‌گیری از داده‌ها"},
    {"key": "restore", "name": "بازیابی", "category": "system", "description": "بازیابی از پشتیبان"},
    {"key": "system_logs", "name": "لاگ سیستم", "category": "system", "description": "لاگ‌های سیستم"},
    {"key": "error_logs", "name": "لاگ خطا", "category": "system", "description": "لاگ‌های خطا"},
    {"key": "resource_monitor", "name": "مانیتور منابع", "category": "system", "description": "پایش منابع سیستم"},
    # ---- analytics ----
    {"key": "message_analytics", "name": "تحلیل پیام", "category": "analytics", "description": "تحلیل پیام‌ها"},
    {"key": "user_analytics", "name": "تحلیل کاربر", "category": "analytics", "description": "تحلیل کاربران"},
    {"key": "chat_analytics", "name": "تحلیل چت", "category": "analytics", "description": "تحلیل چت‌ها"},
    {"key": "activity", "name": "فعالیت", "category": "analytics", "description": "پایش فعالیت"},
    {"key": "command_stats", "name": "آمار دستورات", "category": "analytics", "description": "آمار دستورات"},
    {"key": "module_stats", "name": "آمار ماژول", "category": "analytics", "description": "آمار ماژول‌ها"},
    {"key": "worker_stats", "name": "آمار ورکر", "category": "analytics", "description": "آمار ورکرها"},
    {"key": "usage_report", "name": "گزارش مصرف", "category": "analytics", "description": "گزارش مصرف کاربر"},
    # ---- security ----
    {"key": "roles", "name": "نقش‌ها", "category": "security", "description": "مدیریت نقش‌ها"},
    {"key": "permissions", "name": "مجوزها", "category": "security", "description": "مدیریت مجوزها"},
    {"key": "session_manager", "name": "مدیر نشست", "category": "security", "description": "مدیریت نشست‌ها"},
    {"key": "session_revocation", "name": "ابطال نشست", "category": "security", "description": "ابطال نشست‌ها"},
    {"key": "device_monitoring", "name": "مانیتور دستگاه", "category": "security", "description": "پایش دستگاه‌ها"},
    {"key": "security_logs", "name": "لاگ امنیتی", "category": "security", "description": "لاگ‌های امنیتی"},
    {"key": "rate_limiting", "name": "محدودیت نرخ", "category": "security", "description": "محدودیت نرخ درخواست"},
    {"key": "suspicious_activity", "name": "فعالیت مشکوک", "category": "security", "description": "تشخیص فعالیت مشکوک"},
    # ---- integrations ----
    {"key": "rest_api", "name": "REST API", "category": "integrations", "description": "دسترسی REST API"},
    {"key": "webhooks", "name": "وب‌هوک‌ها", "category": "integrations", "description": "وب‌هوک‌های خروجی"},
    {"key": "external_apis", "name": "APIهای خارجی", "category": "integrations", "description": "اتصال به API خارجی"},
    {"key": "ai_provider", "name": "رابط هوش مصنوعی", "category": "integrations", "description": "اتصال به سرویس AI"},
    {"key": "translation", "name": "رابط ترجمه", "category": "integrations", "description": "سرویس ترجمه"},
    {"key": "url_tools", "name": "ابزار URL", "category": "integrations", "description": "ابزارهای لینک"},
    {"key": "notification", "name": "رابط اطلاع‌رسانی", "category": "integrations", "description": "اعلان‌ها"},
    {"key": "custom_webhooks", "name": "وب‌هوک سفارشی", "category": "integrations", "description": "وب‌هوک سفارشی"},
    # ---- advanced ----
    {"key": "multi_account", "name": "چند حساب", "category": "advanced", "description": "مدیریت چند حساب"},
    {"key": "multi_worker", "name": "چند ورکر", "category": "advanced", "description": "چند ورکر هم‌زمان"},
    {"key": "worker_recovery", "name": "بازیابی ورکر", "category": "advanced", "description": "بازیابی خودکار ورکر"},
    {"key": "load_balancing", "name": "توازن بار", "category": "advanced", "description": "توزیع بار بین ورکرها"},
    {"key": "job_queue", "name": "صف کار", "category": "advanced", "description": "صف کارها"},
    {"key": "priority_queue", "name": "صف اولویت", "category": "advanced", "description": "صف با اولویت"},
    {"key": "failover", "name": "جایگزینی", "category": "advanced", "description": "جایگزینی در خطا"},
    {"key": "health_monitoring", "name": "مانیتور سلامت", "category": "advanced", "description": "پایش سلامت"},
    {"key": "remote_config", "name": "پیکربندی راه دور", "category": "advanced", "description": "پیکربندی از راه دور"},
    {"key": "global_kill_switch", "name": "کلید توقف اضطراری", "category": "advanced", "description": "توقف اضطراری همه سلف‌ها"},
]

CATEGORY_NAMES = {
    "message": "💬 پیام",
    "groups": "👥 گروه",
    "channels": "📢 کانال",
    "automation": "🤖 اتوماسیون",
    "media": "🎬 رسانه",
    "search": "🔍 جستجو",
    "plugins": "🧩 پلاگین",
    "system": "⚙️ سیستم",
    "analytics": "📊 تحلیل",
    "security": "🔐 امنیت",
    "integrations": "🔗 یکپارچه‌سازی",
    "advanced": "🚀 پیشرفته",
}
